# Author: Diogo Lisboa<diogo@dlisboa.com>

# syntax highlighting
"string" = "gray"
"comment" = "gray"
"keyword" = "gray"
"keyword.storage.type" = "white"
"tag" = "gray"

# ui
"ui.background" = {bg="background"}
"ui.text" = "white"
"ui.text.focus" = {bg="darkgray"}
"ui.linenr" = {fg="gray"}
"ui.linenr.selected" = {fg="white"}
"ui.selection" = {bg="gray", fg="black"}
"ui.cursorline" = {bg="darkgray"}
"ui.statusline" = {fg="white", bg="darkgray"}
"ui.statusline.inactive" = {fg="gray", bg="darkgray"}
"ui.virtual" = "gray"
"ui.virtual.ruler" = { bg = "darkgray" }
"ui.cursor" = {bg="cursor", fg="white"}
"ui.debug" = {fg="orange"}
"ui.highlight" = {bg="darkgray"}
"ui.highlight.frameline" = {bg="red"}
"ui.help" = {fg="white", bg="background"}
"ui.popup" = {fg="white", bg="background"}
"ui.menu" = {fg="white", bg="background"}
"ui.menu.selected" = {fg="black", bg="selected"}
"ui.window" = {bg="background"}
"ui.bufferline" = { fg = "white", bg = "gray" }
"ui.bufferline.active" = { fg = "white", bg = "background" }

# error messages
"diagnostic.error" = {fg="white", underline={color="red", style="curl"}}
"diagnostic.warning" = {fg="white", underline={color="orange", style="curl"}}
"diagnostic.hint" = {fg="gray", modifiers=["bold"]}
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

# diff gutter
"diff.plus" = {fg = "green"}
"diff.delta" = {fg = "orange"}
"diff.minus" = {fg = "red"}

[palette]
background = "#080808"
white = "#eeeeee"
gray = "#909090"
darkgray = "#303030"
black = "#000000"
cursor = "#555555"
selected = "#bbbbbb"
red = "#6F2622"
green = "#384F2D"
orange = "#645338"
